source = ./colors.conf

general {
    grace = 300
    hide_cursor = true
}

background {
    path = screenshot
    blur_passes = 3
    blur_size = 8
    brightness = 0.75
}

# Time
label {
    text = $TIME
    font_family = JetBrains Mono Nerd Font
    font_size = 80
    color = $font_color
    position = 0, -150
    halign = center
    valign = top
    shadow_passes = 2
    shadow_color = rgba(0, 0, 0, 0.5)
}

# Date
label {
    text = cmd[update:3600000] date +"%A, %B %d"
    font_family = JetBrains Mono Nerd Font
    font_size = 20
    color = $font_color
    position = 0, -260
    halign = center
    valign = top
    shadow_passes = 2
    shadow_color = rgba(0, 0, 0, 0.5)
}

input-field {
    size = 250, 50
    position = 0, -50
    monitor =
    halign = center
    valign = center
    dots_center = true
    dots_size = 0.25
    fade_on_empty = false
    font_color = $font_color
    font_family = JetBrains Mono Nerd Font
    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 3
    placeholder_text =
    rounding = 15
    shadow_passes = 2
    check_color = $accent_color
    fail_color = $fail_color
    fail_text = <i>try again</i>
    capslock_color = $warn_color
}
